name: Build & Publish compiler package

on:
  push:
    branches:
      - master
    paths:
      - 'src/ronimizy.Razor.Sdk.ModifierTool/**'
      - '.github/workflows/build-sdk-compiler.yaml'
      - 'pack.sh'
      - '*.props'
  
  workflow_dispatch:

env:
  PACKAGE_PREFIX: ronimizy.Razor.Sdk
  PACKAGE_VERSION: 1.0.${{ github.run_number }}-alpha
  PACKAGE_DIR: ./razor/artifacts/packages/Release/Shipping

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Create compiler package
        run: |
          RAZOR_SDK_SKIP_CLEANUP=1 ./pack.sh ${{ env.PACKAGE_PREFIX }} ${{ env.PACKAGE_VERSION }}
          
          mkdir ./packages
          compiler_package=${{ env.PACKAGE_DIR }}/${{ env.PACKAGE_PREFIX }}.Compiler.${{ env.PACKAGE_VERSION }}.nupkg
          cp "$compiler_package" ./packages
          
          echo Packages content
          unzip -v "$compiler_package"
          
          echo Bin content
          find ./razor/artifacts/bin/Microsoft.CodeAnalysis.Razor.Compiler/Release | grep '.*\.dll'
          
          echo # MSBuild content >> $GITHUB_STEP_SUMMARY
          echo ``` >> $GITHUB_STEP_SUMMARY
          cat ./razor/src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/msbuild.log >> $GITHUB_STEP_SUMMARY
          echo ``` >> $GITHUB_STEP_SUMMARY

      - name: Publish compiler package
        run: |
          for file in ./packages/*.nupkg
          do
            dotnet nuget push "${file#/}" --source "nuget.org" --api-key ${{ secrets.NUGET_API_KEY }}
          done